name: Github Actions for testing and linting
on: [push]
jobs:
  Tests and linting:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        python-version: [3.9]

    steps:
      - name: Checkout repo
        uses: actions/checkout@v2
      - name: Set Up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python-version }}
      - name: Install pylint
        uses: BSFishy/pip-action@v1
        with:
          packages: |
            pylint
          requirements: |
            py.requirements/all.txt
            ahorcado
      - name: Display Python version
        run: python -c "import sys; print(sys.version)"
      - name: Run unit tests
        run: python tests/test_ahorcado.py
      - name: Run acceptance tests
        run: invoke test
      - name: Run static code analyzer on Ahorcado package
        run: pylint --exit-zero src
      - name: Run static code analyzer on unit tests
        run: pylint --exit-zero tests/test_ahorcado.py
