name: GitHub Actions Demo
on: [push]
jobs:
  Explore-GitHub-Actions:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        python-version: [3.6, 3.9]

    steps:
      - name: Checkout repo
        uses: actions/checkout@v2
      - name: Set Up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python-version }}
      - name: Display Python version
        run: python -c "import sys; print(sys.version)"
      - name: Run tests
        run: python test_ahorcado.py

    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v1
      - uses: BSFishy/pip-action@v1
      - name: Run static code analyzer on test classes
        with:
          packages: |
            pylint
        run: pylint test_ahorcado.py
      - name: Run static code analyzer on ahorcado classes
        with:
          packages: |
            pylint
        run: pylint ahorcado.py
